trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: ReadKeyVaultSecrets
  steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'SubscriptionConnectiondev'
      KeyVaultName: 'kv-ti-dev-eastus-01'
      SecretsFilter: '*'
      RunAsPreJob: false

  - script: |
      echo "Secret 1: $(Okta-OktaAPIToken)"
    
  displayName: 'Read Secrets from Azure Key Vault'