parameters:
- name: myArray
  type: object
  default:
    - name: "Object 1"
      value: "Value 1"
jobs:
- job: MyJob
  steps:
  - script: |
      echo "Traversing the array of objects"
      for item in ${{ parameters.myArray[0] }};
      do
        echo "item"
      done
    displayName: 'Traverse Array'