trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: ReadKeyVaultSecrets
  steps:
  - task: AzureKeyVault@1
    displayName: 'Read Secrets from Azure Key Vault'
    inputs:
      azureSubscription: 'SubscriptionConnectiondev'
      KeyVaultName: 'kv-ti-dev-eastus-01'
      SecretsFilter: '*'
      RunAsPreJob: false
      
  - task: PowerShell@2
    displayName: 'Powershell script'
    inputs:
      targetType: 'inline'
      script: |
        $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
        $headers.Add("Accept", "application/json")
        $headers.Add("Content-Type", "application/json")
        $headers.Add("Authorization", "SSWS $(Okta-OktaAPIToken)")
        echo "SSWS $(Okta-OktaAPIToken)"
        
        $response = Invoke-RestMethod 'https://dev-92837008.okta.com/api/v1/users?limit=1' -Method 'GET' -Headers $headers
        $response | ConvertTo-Json

  - script: |
      echo "Secret 1: $(Okta-OktaAPIToken)"

    
  

       
