trigger:
  branches:
    include:
    - main
variables:
 - name: domain
   value: https://dev-92837008.okta.com
parameters:
- name: listOfEnv
  type: object
  default:
  - Environment: QA
    Agentpoolname: windows-latest
    AzureSubServiceConName: SubscriptionConnectiondev
    KeyVaultName: AzurePipeline-kv
    Projects:
      - ProjectName: PdfReporting
        KeyName: OktaToken 
        KeyName2: $(domain)  
stages:
- stage: default
  jobs:
  - ${{ each parent in parameters.listOfEnv }} : 
    - job: ReadKeyVaultSecrets
      pool:
       vmImage: ${{ parent.Agentpoolname}}
       steps:
          - task: AzureKeyVault@1
            displayName: 'Read Secrets from Azure Key Vault  ${{ parent.AzureSubServiceConName}}'
            inputs:
             azureSubscription: ${{ parent.AzureSubServiceConName}}
             KeyVaultName:  ${{ parent.KeyVaultName}}
             SecretsFilter: '*'
             RunAsPreJob: false
          - ${{ each project in parent.Projects}}  :
            - task: PowerShell@2
              displayName: 'Powershell script'
              inputs:
               targetType: 'inline'
               script: |
                 $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
                 $headers.Add("Accept", "application/json")
                 $headers.Add("Content-Type", "application/json")
                 $headers.Add("Authorization", "SSWS $(${{project.KeyName}})") 
                 $response = Invoke-RestMethod '${{project.KeyName2}}/api/v1/users?limit=1' -Method 'GET' -Headers $headers
                 $response | ConvertTo-Json
                 