parameters:
- name: myArray
  type: object
  default:
    - name: Object 1
      value: Value 1
    - name: Object 2
      value: Value 2
    - name: Object 3
      value: Value 3
jobs:
- job: MyJob
  steps:
  - script: |
      echo "Traversing the array of objects"
      for item in ${{ parameters.myArray }};
      do
        name=$(echo $item | jq -r '.name')
        value=$(echo $item | jq -r '.value')
        echo "Name: $name, Value: $value"
      done
    displayName: 'Traverse Array'